version: "3.9"
services:
  web:
    container_name: web
    image: ooxyz/sosmed-web:${GIT_COMMIT_SHORT}
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    container_name: db
    image: ooxyz/sosmed-db:${GIT_COMMIT_SHORT}